name: Delete Folder

on:
  workflow_dispatch:
    inputs:
      folder_name:
        description: 'پوشه مورد نظر'
        required: true
        type: choice
        options:
          - 'temp'
          - 'cache'
          - 'logs'
          - 'node_modules'
          - 'dist'

jobs:
  delete:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Delete folder
      run: rm -rf ${{ github.event.inputs.folder_name }}